---
- name: Check if Sybase DB was already installed
  stat:
    path: "/sybase/{{ sap_sid|upper }}/ASE-16_0"
  register: syb_install_status

- name: Generate parameter file for sapinst
  template:
    src: sapinst.cfg
    dest: "{{ nwapp_kit }}/inifile.params"
  when: not syb_install_status.stat.exists

- name: Start SAP ASE DB installation
  shell: "{{ nwapp_kit }}/swpm/sapinst SAPINST_INPUT_PARAMETERS_URL={{ nwapp_kit }}/inifile.params SAPINST_EXECUTE_PRODUCT_ID={{ sap_product_id }} SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false"
  when: not syb_install_status.stat.exists

- name: Remove virtual hostnames to /etc/hosts file
  blockinfile:
    path: /etc/hosts
    block: |
      {{ app_iphost1 }} {{ cname_ascs }} {{ cname_ascs }}.{{ domain_name }}
      {{ app_iphost2 }} {{ cname_ers }} {{ cname_ers }}.{{ domain_name }}
    state: absent
...
