---
- name: Gather current memory and swap variables
  setup: gather_subset="all"

- name: Calculate recommended tmpfs size
  set_fact: tmpfs_size="{{ ((ansible_memtotal_mb + ansible_memory_mb.swap.total) * 0.75 / 1024) | round | int}}"

- name: Mount tmpfs and add it to /etc/fstab
  mount:
    path: /dev/shm
    src: tmpfs
    fstype: tmpfs
    opts: "size={{ tmpfs_size }}G"
    state: mounted
...