---
- name: Create /usr/sap/kit directory
  file:
    path: "{{ nwapp_kit }}"
    state: directory
    mode: 0777

- name: Create /usr/sap/kit/swpm directory
  file:
    path: "{{ nwapp_kit }}/swpm"
    state: directory
    mode: 0777

- name: Create /usr/sap/kit/asedb directory
  file:
    path: "{{ nwapp_kit }}/asedb"
    state: directory
    mode: 0777

- name: Copy "{{ kit_sapcar_file }}" kit to target
  copy:
    src: "{{ kit_sapcar_file }}"
    dest: "{{ nwapp_kit }}/sapcar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_swpm_file }}" kit to target
  copy:
    src: "{{ kit_swpm_file }}"
    dest: "{{ nwapp_kit }}/swpm.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_sapexe_file }}" kit to target
  copy:
    src: "{{ kit_sapexe_file }}"
    dest: "{{ nwapp_kit }}/sapexe.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_sapexedb_file }}" kit to target
  copy:
    src: "{{ kit_sapexedb_file }}"
    dest: "{{ nwapp_kit }}/sapexedb.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_saphotagent_file }}" kit to target
  copy:
    src: "{{ kit_saphotagent_file }}"
    dest: "{{ nwapp_kit }}/saphotagent.sar"
    owner: root
    group: root
    mode: 0777

- name: Copy "{{ kit_ase_file }}" kit to target
  copy:
    src: "{{ kit_ase_file }}/"
    dest: "{{ nwapp_kit }}/asedb.zip"
    owner: root
    group: root
    mode: 0777

- name: Extract ASEDB archive
  command: "unzip {{ nwapp_kit }}/asedb.zip -d {{ nwapp_kit }}/asedb"

- name: Extract SWPM archive
  command: "{{ nwapp_kit }}/sapcar -xf {{ nwapp_kit }}/swpm.sar -R {{ nwapp_kit }}/swpm"
...
