---
- name: Check /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ app_iphost1 }} {{ cname_ascs }} {{ cname_ascs }}.{{ domain_name }}"
    state: absent
  check_mode: yes
  register: presence
  notify:
    - Configure Secure Store User
    - Configure Secure Store Password
    - Generate Fault Manager profile
    - Install Fault Manager
    - Restart ASCS cluster resource
    - Remove virtual hostnames to /etc/hosts file
...
