############################################################
# The variables and data sources used in VPC infra Modules. 
############################################################

variable "PRIVATE_SSH_KEY" {
	type		= string
	description = "Input your id_rsa private key pair content in OpenSSH format.This private key it is used only during the terraform provisioning and it is recommended to be changed after the SAP deployment."
	nullable = false
	validation {
	condition = length(var.PRIVATE_SSH_KEY) >= 64 && var.PRIVATE_SSH_KEY != null && length(var.PRIVATE_SSH_KEY) != 0 || contains(["n.a"], var.PRIVATE_SSH_KEY )
	error_message = "The content for private_ssh_key variable must be completed in OpenSSH format."
      }
}

variable "ID_RSA_FILE_PATH" {
    default = "ansible/id_rsa"
    nullable = false
    description = "The file path for private_ssh_key will be automatically generated by default. If it is changed, it must contain the relative path from git repo folders. Example: ansible/id_rsa_ase-syb_ha"
}

variable "SSH_KEYS" {
	type		= list(string)
	description = "List of SSH Keys UUIDs that are allowed to SSH as root to the VSI. The SSH Keys should be created for the same region as the VSI. The list of available SSH Keys UUIDs: https://cloud.ibm.com/vpc-ext/compute/sshKeys"
	validation {
		condition     = var.SSH_KEYS == [] ? false : true && var.SSH_KEYS == [""] ? false : true
		error_message = "At least one SSH KEY is needed to be able to access the VSI."
	}
}

variable "BASTION_FLOATING_IP" {
	type		= string
	description = "Input the BASTION FLOATING IP. It can be copied from the Bastion Server Deployment \"OUTPUTS\" at the end of \"Apply plan successful\" message. "
	nullable = false
	validation {
        condition = can(regex("^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$",var.BASTION_FLOATING_IP)) || contains(["localhost"], var.BASTION_FLOATING_IP ) && var.BASTION_FLOATING_IP!= null
        error_message = "Incorrect format for variable: BASTION_FLOATING_IP."
      }
}

variable "RESOURCE_GROUP" {
  type        = string
  description = "EXISTING Resource group, previously created by the user. The list of available Resource Groups: https://cloud.ibm.com/account/resource-groups"
  default     = "Default"
}

variable "REGION" {
	type		= string
	description	= "Region for the VSI. Supported regions: https://cloud.ibm.com/docs/containers?topic=containers-regions-and-zones#zones-vpc"
	validation {
		condition     = contains(["au-syd", "jp-osa", "jp-tok", "eu-de", "eu-gb", "ca-tor", "us-south", "us-east", "br-sao"], var.REGION )
		error_message = "The REGION must be one of: au-syd, jp-osa, jp-tok, eu-de, eu-gb, ca-tor, us-south, us-east, br-sao."
	}
}

variable "ZONE" {
	type		= string
	description	= "Availability zone for VSI. Supported zones: https://cloud.ibm.com/docs/containers?topic=containers-regions-and-zones#zones-vpc"
	validation {
		condition     = length(regexall("^(au-syd|jp-osa|jp-tok|eu-de|eu-gb|ca-tor|us-south|us-east|br-sao)-(1|2|3)$", var.ZONE)) > 0
		error_message = "The ZONE is not valid."
	}
}

variable "VPC" {
	type		= string
	description = "EXISTING VPC, previously created by the user in the same region as the VSI. The list of available VPCs: https://cloud.ibm.com/vpc-ext/network/vpcs"
	validation {
		condition     = length(regexall("^([a-z]|[a-z][-a-z0-9]*[a-z0-9]|[0-9][-a-z0-9]*([a-z]|[-a-z][-a-z0-9]*[a-z0-9]))$", var.VPC)) > 0
		error_message = "The VPC name is not valid."
	}
}

variable "SUBNET" {
	type		= string
	description = "EXISTING Subnet in the same region and zone as the VSI, previously created by the user. The list of available Subnets: https://cloud.ibm.com/vpc-ext/network/subnets"
	validation {
		condition     = length(regexall("^([a-z]|[a-z][-a-z0-9]*[a-z0-9]|[0-9][-a-z0-9]*([a-z]|[-a-z][-a-z0-9]*[a-z0-9]))$", var.SUBNET)) > 0
		error_message = "The SUBNET name is not valid."
	}
}

variable "SECURITY_GROUP" {
	type		= string
	description = "EXISTING Security group, previously created by the user in the same VPC. It can be copied from the Bastion Server Deployment \"OUTPUTS\" at the end of \"Apply plan successful\" message. The list of available Security Groups: https://cloud.ibm.com/vpc-ext/network/securityGroups"
	validation {
		condition     = length(regexall("^([a-z]|[a-z][-a-z0-9]*[a-z0-9]|[0-9][-a-z0-9]*([a-z]|[-a-z][-a-z0-9]*[a-z0-9]))$", var.SECURITY_GROUP)) > 0
		error_message = "The SECURITY_GROUP name is not valid."
	}
}

variable "DOMAIN_NAME" {
	type		= string
	description	= "The DOMAIN_NAME variable should contain at least one \".\" as a separator. It is a private domain and it is not reachable to and from the outside world.The DOMAIN_NAME variable could be like a subdomain name. Ex.: staging.example.com. You can't use a domain name that is already in use."
	nullable = false
	default = ""
	validation {
		condition     =  length(var.DOMAIN_NAME) > 2  && length (regex("^[a-z]*||^[0-9]*||\\.||\\-", var.DOMAIN_NAME)) > 0  && length (regex("[\\.]", var.DOMAIN_NAME)) > 0  && length (regexall("[\\&]|[\\%]|[\\!]|[\\@]|[\\#]|[\\*]|[\\^]", var.DOMAIN_NAME)) == 0
		error_message = "The DOMAIN_NAME variable should not be empty and must contain at least one \".\" as a separator and no special chars are allowed."
	}
}

locals {
	ASCS-VIRT-HOSTNAME = "sap${var.SAP_SID}ascs"
	ERS-VIRT-HOSTNAME = "sap${var.SAP_SID}ers"
	SYBASE-VIRT-HOSTNAME = "db${var.SAP_SID}syb"
}

variable "ASCS_VIRT_HOSTNAME" {
	type		= string
	description	= "Private SubDomain Name"
	nullable = false
	default = "sapascs"
	validation {
		condition     =  length(var.ASCS_VIRT_HOSTNAME) > 2  && length (regex("^[a-z]*||^[0-9]*", var.ASCS_VIRT_HOSTNAME)) > 0  && length (regexall("[\\&]|[\\%]|[\\!]|[\\@]|[\\#]|[\\*]|[\\^]", var.ASCS_VIRT_HOSTNAME)) == 0
		error_message = "The SUBDOMAIN_NAME variable should not be empty and no special chars are allowed."
	}
}

output VIRT-HOSTNAME-ASCS {
  value = var.ASCS_VIRT_HOSTNAME != "sapascs" ? var.ASCS_VIRT_HOSTNAME : lower ("${local.ASCS-VIRT-HOSTNAME}")
}

variable "ERS_VIRT_HOSTNAME" {
	type		= string
	description	= "Private SubDomain Name"
	nullable = false
	default = "sapers"
	validation {
		condition     =  length(var.ERS_VIRT_HOSTNAME) > 2  && length (regex("^[a-z]*||^[0-9]*", var.ERS_VIRT_HOSTNAME)) > 0 && length (regexall("[\\&]|[\\%]|[\\!]|[\\@]|[\\#]|[\\*]|[\\^]", var.ERS_VIRT_HOSTNAME)) == 0
		error_message = "The SUBDOMAIN_NAME variable should not be empty and no special chars are allowed."
	}
}

output VIRT-HOSTNAME-ERS {
  value = var.ERS_VIRT_HOSTNAME != "sapers" ? var.ERS_VIRT_HOSTNAME : lower ("${local.ERS-VIRT-HOSTNAME}")
}

locals {
	DB-HOSTNAME-1 = "sybdb-${var.SAP_SID}-1"
	DB-HOSTNAME-2 = "sybdb-${var.SAP_SID}-2"
	APP-HOSTNAME-1 = "sapapp-${var.SAP_SID}-1"
	APP-HOSTNAME-2 = "sapapp-${var.SAP_SID}-2"
	
}

variable "DB_PROFILE" {
	type		= string
	description = "The DB VSI profile. Supported profiles for DB VSI: bx2-4x16. The list of available profiles: https://cloud.ibm.com/docs/vpc?topic=vpc-profiles&interface=ui"
	default		= "bx2-4x16"
}

variable "DB_IMAGE" {
	type		= string
	description = "OS image for DB VSI. Supported OS images for DB VSIs: ibm-redhat-8-6-amd64-sap-hana-2, ibm-redhat-8-4-amd64-sap-hana-4. The list of available VPC Operating Systems supported by SAP: SAP note '2927211-SAP Applications on IBM Virtual Private Cloud (VPC) Infrastructure environment' https://launchpad.support.sap.com/#/notes/2927211; The list of all available OS images: https://cloud.ibm.com/docs/vpc?topic=vpc-about-images"
	default		= "ibm-redhat-8-6-amd64-sap-hana-4"
}

variable "DB_HOSTNAME_1" {
	type		= string
	description = "SYBASE Cluster VSI1 Hostname. The hostname should be up to 13 characters, as required by SAP. If you leave the Default Value \"sybdb-1\" then, the variable DB_HOSTNAME_1 = \"sybdb-$your_sap_sid-1\""
	default = "sybdb-1"
	validation {
		condition     = length(var.DB_HOSTNAME_1) <= 13 && length(regexall("^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]*[a-zA-Z0-9])\\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\\-]*[A-Za-z0-9])$", var.DB_HOSTNAME_1)) > 0
		error_message = "The DB-HOSTNAME is not valid."
	}
}

output SYBASE-DB-HOSTNAME-VSI1 {
  value = var.DB_HOSTNAME_1 != "sybdb-1" ? var.DB_HOSTNAME_1 : lower ("${local.DB-HOSTNAME-1}")
}

variable "DB_HOSTNAME_2" {
	type		= string
	description = "SYBASE Cluster VSI2 Hostname. The hostname should be up to 13 characters, as required by SAP. If you leave the Default Value \"sybdb-2\" then, the variable DB_HOSTNAME_2 = \"sybdb-$your_sap_sid-2\""
	default = "sybdb-2"
	nullable = true
	validation {
		condition     = length(var.DB_HOSTNAME_2) <= 13 && length(regexall("^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]*[a-zA-Z0-9])\\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\\-]*[A-Za-z0-9])$", var.DB_HOSTNAME_2)) > 0
		error_message = "The DB-HOSTNAME is not valid."
	}
}

output SYBASE-DB-HOSTNAME-VSI2 {
  value = var.DB_HOSTNAME_2 != "sybdb-2" ? var.DB_HOSTNAME_2 : lower ("${local.DB-HOSTNAME-2}")
}

variable "APP_PROFILE" {
	type		= string
	description = "The APP VSI profile. Supported profiles: bx2-4x16. The list of available profiles: https://cloud.ibm.com/docs/vpc?topic=vpc-profiles&interface=ui"
	default		= "bx2-4x16"
}

variable "APP_IMAGE" {
	type		= string
	description = "OS image for SAP APP VSI. Supported OS images for APP VSIs: ibm-redhat-8-6-amd64-sap-hana-2, ibm-redhat-8-4-amd64-sap-hana-4. The list of available VPC Operating Systems supported by SAP: SAP note '2927211-SAP Applications on IBM Virtual Private Cloud (VPC) Infrastructure environment' https://launchpad.support.sap.com/#/notes/2927211; The list of all available OS images: https://cloud.ibm.com/docs/vpc?topic=vpc-about-images"
	default		= "ibm-redhat-8-6-amd64-sap-hana-4"
}

variable "APP_HOSTNAME_1" {
	type		= string
	description = "The Application Cluster VSI1 Hostname. The hostname should be up to 13 characters, as required by SAP. If you leave the Default Value \"sapapp-1\" then, the variable APP_HOSTNAME_1 = \"sapapp-$your_sap_sid-1\""
	default = "sapapp-1"
	validation {
		condition     = length(var.APP_HOSTNAME_1) <= 13 && length(regexall("^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]*[a-zA-Z0-9])\\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\\-]*[A-Za-z0-9])$", var.APP_HOSTNAME_1)) > 0
		error_message = "The APP-HOSTNAME is not valid."
	}
}

output SAP-APP-HOSTNAME-VSI1 {
  value = var.APP_HOSTNAME_1 != "sapapp-1" ? var.APP_HOSTNAME_1 : lower ("${local.APP-HOSTNAME-1}")
}

variable "APP_HOSTNAME_2" {
	type		= string
	description = "The Application Cluster VSI2 Hostname. The hostname should be up to 13 characters, as required by SAP. If you leave the Default Value \"sapapp-2\" then, the variable APP_HOSTNAME_2 = \"sapapp-$your_sap_sid-2\""
	default = "sapapp-2"
	nullable = true
	validation {
		condition     = length(var.APP_HOSTNAME_2) <= 13 && length(regexall("^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]*[a-zA-Z0-9])\\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\\-]*[A-Za-z0-9])$", var.APP_HOSTNAME_2)) > 0
		error_message = "The APP-HOSTNAME is not valid."
	}
}

output SAP-APP-HOSTNAME-VSI2 {
  value = var.APP_HOSTNAME_2 != "sapapp-2" ? var.APP_HOSTNAME_2 : lower ("${local.APP-HOSTNAME-2}")
}

locals {
  SAP-ALB-ASCS = "sap-alb-ascs"
  SAP-ALB-ERS = "sap-alb-ers"
}

data "ibm_is_lb" "alb-ascs" {
  depends_on = [module.alb-prereq]
  name    = lower ("${local.SAP-ALB-ASCS}-${var.SAP_SID}")
}

data "ibm_is_lb" "alb-ers" {
  depends_on = [module.alb-prereq]
  name    = lower ("${local.SAP-ALB-ERS}-${var.SAP_SID}")
}

###

data "ibm_is_instance" "app-vsi-1" {
  depends_on = [module.app-vsi]
  name    =  var.APP_HOSTNAME_1 != "sapapp-1" ? var.APP_HOSTNAME_1 : lower ("${local.APP-HOSTNAME-1}")
}

data "ibm_is_instance" "app-vsi-2" {
  depends_on = [module.app-vsi]
  name    = var.APP_HOSTNAME_2 != "sapapp-2" ? var.APP_HOSTNAME_2 : lower ("${local.APP-HOSTNAME-2}")
}

data "ibm_is_instance" "db-vsi-1" {
  depends_on = [module.db-vsi]
  name    =  var.DB_HOSTNAME_1 != "sybdb-1" ? var.DB_HOSTNAME_1 : lower ("${local.DB-HOSTNAME-1}")
}

data "ibm_is_instance" "db-vsi-2" {
  depends_on = [module.db-vsi]
  name    = var.DB_HOSTNAME_2 != "sybdb-2" ? var.DB_HOSTNAME_2 : lower ("${local.DB-HOSTNAME-2}")
}

############################################################
# The variables and data sources used in File_Share Module. 
############################################################

variable "SHARE_PROFILE" {
  description = "The profile for File Share storage. More details on: https://cloud.ibm.com/docs/vpc?topic=vpc-file-storage-profiles&interface=ui#dp2-profile."
  type        = string
  default     = "dp2"
}

data "ibm_is_vpc" "vpc" {
  name		= var.VPC
}

data "ibm_resource_group" "group" {
  name		= var.RESOURCE_GROUP
}

variable "USRSAP_AS1" {
  description = "Custom File Share size for SAP mount: USRSAP-AS1"
  type        = number
  default = 20
}

variable "USRSAP_AS2" {
  description = "Custom File Share size for SAP mount: USRSAP-AS2"
  type        = number
  default = 20
}

variable "USRSAP_SAPASCS" {
  description = "Custom File Share size for SAP mount:  USRSAP-SAPASCS"
  type        = number
  default = 20
}

variable "USRSAP_SAPERS" {
  description = "Custom File Share size for SAP mount:  USRSAP-SAPERS"
  type        = number
  default = 20
}

variable "USRSAP_SAPMNT" {
  description = "Custom File Share size for SAP mount:  USRSAP-SAPMNT"
  type        = number
  default = 20
}

variable "USRSAP_SAPSYS" {
  description = "Custom File Share size for SAP mount: USRSAP-SAPSYS"
  type        = number
  default = 20
}

variable "USRSAP_TRANS" {
  description = "Custom File Share size for SAP mount: USRSAP-TRANS"
  type        = number
  default = 80
}

##############################################################
# The variables and data sources used in SAP Ansible Modules.
##############################################################

variable "SAP_ASCS_INSTANCE_NUMBER" {
	type		= string
	description = "Technical identifier for internal processes of ASCS."
	default		= "00"
	validation {
		condition     = var.SAP_ASCS_INSTANCE_NUMBER >= 0 && var.SAP_ASCS_INSTANCE_NUMBER <=97
		error_message = "The SAP_ASCS_INSTANCE_NUMBER is not valid."
	}
}

variable "SAP_ERS_INSTANCE_NUMBER" {
	type		= string
	description = "Technical identifier for internal processes of ERS."
	default		= "01"
	validation {
		condition     = var.SAP_ERS_INSTANCE_NUMBER >= 00 && var.SAP_ERS_INSTANCE_NUMBER <=99
		error_message = "The SAP_ERS_INSTANCE_NUMBER is not valid."
	}
}

variable "SAP_CI_INSTANCE_NUMBER" {
	type		= string
	description = "Technical identifier for internal processes of PAS."
	default		= "10"
	validation {
		condition     = var.SAP_CI_INSTANCE_NUMBER >= 00 && var.SAP_CI_INSTANCE_NUMBER <=99
		error_message = "The SAP_CI_INSTANCE_NUMBER is not valid."
	}
}

variable "SAP_AAS_INSTANCE_NUMBER" {
	type		= string
	description = "Technical identifier for internal processes of AAS."
	default		= "20"
	validation {
		condition     = var.SAP_AAS_INSTANCE_NUMBER >= 00 && var.SAP_AAS_INSTANCE_NUMBER <=99
		error_message = "The SAP_AAS_INSTANCE_NUMBER is not valid."
	}
}

variable "SAP_SID" {
	type		= string
	description = "The SAP system ID identifies the entire SAP system."
	default		= "NWD"
	validation {
		condition     = length(regexall("^[a-zA-Z][a-zA-Z0-9][a-zA-Z0-9]$", var.SAP_SID)) > 0 && !contains(["ADD", "ALL", "AMD", "AND", "ANY", "ARE", "ASC", "AUX", "AVG", "BIT", "CDC", "COM", "CON", "DBA", "END", "EPS", "FOR", "GET", "GID", "IBM", "INT", "KEY", "LOG", "LPT", "MAP", "MAX", "MIN", "MON", "NIX", "NOT", "NUL", "OFF", "OLD", "OMS", "OUT", "PAD", "PRN", "RAW", "REF", "ROW", "SAP", "SET", "SGA", "SHG", "SID", "SQL", "SUM", "SYS", "TMP", "TOP", "UID", "USE", "USR", "VAR"], var.SAP_SID)
		error_message = "The sap_sid is not valid."
	}
}

variable "SAP_MAIN_PASSWORD" {
	type		= string
	sensitive = true
	description = "Common password for all users that are created during the installation. It must be 8 to 14 characters long, it must contain at least one digit (0-9) and one uppercase letter, it must not contain \\ (backslash) and \" (double quote)."
	validation {
		condition     = length(regexall("^(.{0,9}|.{15,}|[^0-9]*)$", var.SAP_MAIN_PASSWORD)) == 0 && length(regexall("^[^0-9_][0-9a-zA-Z@#$_]+$", var.SAP_MAIN_PASSWORD)) > 0 && length(regexall("[A-Z]", var.SAP_MAIN_PASSWORD)) > 0
		error_message = "The SAP_MAIN_PASSWORD is not valid."
	}
}

variable "HA_PASSWORD" {
	type		= string
	sensitive = true
	description = "HA cluster password. It must be 8 to 14 characters long, it must contain at least one digit (0-9), it must not contain \\ (backslash) and \" (double quote)."
	validation {
		condition     = length(regexall("^(.{0,9}|.{15,}|[^0-9]*)$", var.HA_PASSWORD)) == 0 && length(regexall("^[^0-9_][0-9a-zA-Z@#$_]+$", var.HA_PASSWORD)) > 0
		error_message = "The HA_PASSWORD is not valid."
	}
}

variable "KIT_SAPCAR_FILE" {
	type		= string
	description = "Path to sapcar binary, as downloaded from SAP Support Portal."
	default		= "/storage/NW75SYB/SAPCAR_1010-70006178.EXE"
}

variable "KIT_SWPM_FILE" {
	type		= string
	description = "Path to SWPM archive (SAR), as downloaded from SAP Support Portal."
	default		= "/storage/NW75SYB/SWPM10SP38_0-20009701.SAR"
}

variable "KIT_SAPHOSTAGENT_FILE" {
	type		= string
	description = "Path to SAP Host Agent archive (SAR), as downloaded from SAP Support Portal."
	default		= "/storage/NW75SYB/SAPHOSTAGENT61_61-80004822.SAR"
}

variable "KIT_SAPEXE_FILE" {
	type		= string
	description = "Path to SAP Kernel OS archive (SAR), as downloaded from SAP Support Portal."
	default		= "/storage/NW75SYB/KERNEL/754UC/SAPEXE_200-80007612.SAR"
}

variable "KIT_SAPEXEDB_FILE" {
	type		= string
	description = "Path to SAP Kernel DB archive (SAR), as downloaded from SAP Support Portal."
	default		= "/storage/NW75SYB/KERNEL/754UC/SAPEXEDB_200-80007655.SAR"
}

variable "KIT_IGSEXE_FILE" {
	type		= string
	description = "Path to IGS archive (SAR), as downloaded from SAP Support Portal."
	default		= "/storage/NW75SYB/KERNEL/754UC/igsexe_2-80007786.sar"
}

variable "KIT_IGSHELPER_FILE" {
	type		= string
	description = "Path to IGS Helper archive (SAR), as downloaded from SAP Support Portal."
	default		= "/storage/NW75SYB/igshelper_17-10010245.sar"
}

variable "KIT_ASE_FILE" {
	type		= string
	description = "Path to SAP ASE DB archive (ZIP), as downloaded from SAP Support Portal."
	default		= "/storage/NW75SYB/51056521_1_16_0_04_04.ZIP"
}

variable "KIT_EXPORT_DIR" {
	type		= string
	description = "Path to Netweaver Installation Export dir. The archives downloaded from SAP Support Portal should be present in this path."
	default		= "/storage/NW75SYB/EXP"
}