---
- name: Check if /usr/sap/kit directory exists on PAS server
  stat:
    path: "/usr/sap/kit"
  register: kit_path_pas

- name: Restart PAS instance
  shell: "sapcontrol -nr {{ sap_ci_instance_number }} -function RestartInstance"
  become: true
  become_method: su
  become_flags: "-"
  become_user: "{{ sap_sid | lower }}adm"
  when: kit_path_pas.stat.exists
...
