---
- name: Check SAP PAS installation status
  stat:
    path: "/usr/sap/{{ sap_sid | upper }}/D{{ sap_ci_instance_number }}/exe/sapstartsrv"
  register: pas_stat_result

- name: Generate parameter file for sapinst
  template:
    src: sapinst.cfg
    dest: "{{ nwapp_kit }}/inifile.params"
  when: not pas_stat_result.stat.exists

- name: Start SAP NW PAS installation
  shell: "{{ nwapp_kit }}/swpm/sapinst SAPINST_INPUT_PARAMETERS_URL={{ nwapp_kit }}/inifile.params SAPINST_EXECUTE_PRODUCT_ID={{ sap_product_id }} SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false"
  when: not pas_stat_result.stat.exists

- name: Cleanup
  file:
    path: "{{ nwapp_kit }}"
    state: absent
...
