---
- name: Configure resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    line: "search {{ domain_name }}"

- name: Add the domain name to network interface config
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: "DOMAIN=\"{{ domain_name }}\""

- name: Check if HA was configured on Secondary DB
  stat:
    path: "/sybase/{{ sap_sid | upper }}/sapdbctrl-config/hb/SYBHA_{{ sap_sid | upper }}.PFL"
  register: secondary_ha_cfg

- name: Restart the network service
  systemd:
    name: NetworkManager.service
    state: restarted
  when: not secondary_ha_cfg.stat.exists

- name: Generate HADR response file
  template:
    src: setup_hadr.cfg
    dest: "{{ hadr_response_file }}"
  when: not secondary_ha_cfg.stat.exists

- name: Configure HADR on Secondary DB
  shell: "setuphadr {{ hadr_response_file }}"
  become: true
  become_method: su
  become_flags: "-"
  become_user: "syb{{ sap_sid | lower }}"
  when: not secondary_ha_cfg.stat.exists
...
