---
- name: Create the filesystem cluster resource for ERS
  shell: |
      pcs resource create fs_{{ sap_sid | upper }}_ERS Filesystem device='{{ sapers_mount_path }}' \
      directory='/usr/sap/{{ sap_sid | upper }}/ERS{{ sap_ers_instance_number }}' fstype='nfs' force_unmount=safe options='sec=sys,vers=4.1' \
      op start interval=0 timeout=60 op stop interval=0 timeout=120 op monitor interval=200 timeout=105 \
      --group group_{{ sap_sid | upper }}_ERS

- name: Add virtual hostnames to /etc/hosts file
  blockinfile:
    path: /etc/hosts
    block: |
      {{ app_iphost1 }} {{ cname_ascs }} {{ cname_ascs }}.{{ domain_name }}
      {{ app_iphost2 }} {{ cname_ers }} {{ cname_ers }}.{{ domain_name }}

- name: Import install kit
  include_tasks: "install_kit.yml"

- name: Import sapusers
  include_tasks: "sapusers.yml"

- name: Import permissions
  include_tasks: "permissions.yml"

- name: Create /usr/sap/lib directory
  file:
    path: /usr/sap/lib
    state: directory
    owner: "{{ sap_sid | lower }}adm"
    group: sapsys
    mode: 0775

- name: Create symlink to compat library
  file:
    src: /opt/rh/SAP/lib64/compat-sap-c++-10.so
    dest: /usr/sap/lib/libstdc++.so.6
    state: link

- name: Generate parameter file for sapinst
  template:
      src: ersconfig.cfg
      dest: "{{ sap_kit }}/ersconfig.params"

- name: Start SAP NW ERS installation
  shell: "{{ sap_kit }}/swpm/sapinst SAPINST_USE_HOSTNAME={{ cname_ers }} SAPINST_INPUT_PARAMETERS_URL={{ sap_kit }}/ersconfig.params SAPINST_EXECUTE_PRODUCT_ID={{ sap_product_id }} SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false"

- name: Create the cluster resource for ERS
  shell: |
      pcs resource create rsc_sap_{{ sap_sid | upper }}_ERS{{ sap_ers_instance_number }} SAPInstance \
      InstanceName={{ sap_sid | upper }}_ERS{{ sap_ers_instance_number }}_{{ cname_ers }} START_PROFILE='/sapmnt/{{ sap_sid | upper }}/profile/{{ sap_sid | upper }}_ERS{{ sap_ers_instance_number }}_{{ cname_ers }}' \
      AUTOMATIC_RECOVER=false IS_ERS=true \
      op monitor interval=20 on-fail=restart timeout=105 op start interval=0 timeout=600 op stop interval=0 timeout=600 \
      --group group_{{ sap_sid | upper }}_ERS

- name: Configure resource stickiness for ASCS
  shell: |
      pcs resource meta group_{{ sap_sid | upper }}_ASCS resource-stickiness=3000 

- name: Configure resource stickiness for ERS
  shell: |
      pcs resource meta rsc_sap_{{ sap_sid | upper }}_ERS{{ sap_ers_instance_number }} resource-stickiness=3000

- name: Configure SAP cluster parameters
  shell: |
      pcs constraint colocation add group_{{ sap_sid | upper }}_ERS with group_{{ sap_sid | upper }}_ASCS -5000
      pcs constraint order start group_{{ sap_sid | upper }}_ASCS then start group_{{ sap_sid | upper }}_ERS kind=Optional symmetrical=false
      pcs constraint order start group_{{ sap_sid | upper }}_ASCS then stop group_{{ sap_sid | upper }}_ERS kind=Optional symmetrical=false

- name: Restart ASCS cluster resource
  shell: |
      pcs resource restart rsc_sap_{{ sap_sid | upper }}_ASCS{{ sap_ascs_instance_number }}

- name: Adjust sap services file
  lineinfile:
    path: /usr/sap/sapservices
    line: "LD_LIBRARY_PATH=/usr/sap/{{ sap_sid | upper }}/ASCS{{ sap_ascs_instance_number }}/exe:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; /usr/sap/{{ sap_sid | upper }}/ASCS{{ sap_ascs_instance_number }}/exe/sapstartsrv pf=/usr/sap/{{ sap_sid | upper }}/SYS/profile/{{ sap_sid | upper }}_ASCS{{ sap_ascs_instance_number }}_{{ cname_ascs }} -D -u {{ sap_sid | lower }}adm"

- name: Remove virtual hostnames to /etc/hosts file
  blockinfile:
    path: /etc/hosts
    block: |
      {{ app_iphost1 }} {{ cname_ascs }} {{ cname_ascs }}.{{ domain_name }}
      {{ app_iphost2 }} {{ cname_ers }} {{ cname_ers }}.{{ domain_name }}
    state: absent
...
