---
- name: Configure cluster authentication
  shell: |
    pcs host auth {{ app_hostname1 }} {{ app_hostname2 }} -u hacluster -p {{ ha_password }}

- name: Cluster setup
  shell: |
    pcs cluster setup ha-sap {{ app_hostname1 }} {{ app_hostname2 }} totem token=30000

- name: Cluster startup
  shell: |
    pcs cluster start --all

- name: Cluster parameters
  shell: |
    pcs resource defaults update resource-stickiness=1
    pcs resource defaults update migration-threshold=3

- name: Configure fencing agent
  shell: |
    pcs stonith create ha-sap-fa fence_ibm_vpc apikey={{ api_key }} \
    limit=1 region={{ region }} pcmk_reboot_action=off \ 
    pcmk_host_map='{{ app_hostname1 }}:{{ app_instanceid1 }};{{ app_hostname2 }}:{{ app_instanceid2 }}' \
    verbose=1 op monitor interval=900s
...
