---
- name: Tuning Red Hat Enterprise Linux for Sybase Databases (RedHat KB 69988)
  sysctl:
    sysctl_file: /etc/sysctl.d/ase.conf
    name: "{{ kernel_param.name }}"
    value: "{{ kernel_param.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - { name: vm.swappiness, value: 10 }
    - { name: vm.dirty_background_ratio, value: 3 }
    - { name: vm.dirty_ratio, value: 40 }
    - { name: vm.dirty_expire_centisecs, value: 500 }
    - { name: vm.dirty_writeback_centisecs, value: 100 }
  loop_control:
    loop_var: kernel_param  
...
