---
- name: Restart AAS instance
  shell: "sapcontrol -nr {{ sap_aas_instance_number }} -function RestartInstance"
  become: true
  become_method: su
  become_flags: "-"
  become_user: "{{ sap_sid | lower }}adm"
...
