#### HA Infra variables.

resource "local_file" "ha_ansible_dns-vars" {
  content = <<-DOC
---
#Ansible vars_file containing variable values passed from Terraform.
#Generated by "terraform plan&apply" command.

# DNS variables
domain_name: "${var.DOMAIN_NAME}"
cname_ascs: "${var.ASCS-VIRT-HOSTNAME}"
cname_ers: "${var.ERS-VIRT-HOSTNAME}"
...
    DOC
  filename = "ansible/dns-vars.yml"
}