---
- hosts: sybdb_iphost2
  gather_facts: true
  pre_tasks:
    - name: Import playbook variables
      include_vars: "{{ item }}"
      loop:
        - "sap-vars.yml"
        - "hainfra-vars.yml"

  roles:
    - asesaptunesecondary
    - cleanup
...
