---
- hosts: sybdb_iphost1,sybdb_iphost2
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Import playbook variables
      include_vars: "{{ item }}"
      loop:
        - "sap-vars.yml"
        - "fileshares-vars.yml"
        - "hainfra-vars.yml"
        - "dns-vars.yml"
  roles:
    - asedbreq
    - resolvehostname
    - asedbfs
...
